# hookの種類
#
# |   hookの名前   |            実行されるタイミング            |lazy OFF|lazy ON|
# |----------------|--------------------------------------------|--------|-------|
# |hook_add        |プラグインが dein.vim によって追加されたとき|OK      |OK     |
# |hook_source     |プラグインが読み込まれる直前                |NG      |OK     |
# |hook_post_source|プラグインが読み込まれた直後                |NG      |OK     |
# |hook_post_update|プラグインが更新された直後                  |OK      |OK     |
# |hook_done_update|プラグイン全ての更新が終わった直後          |OK      |OK     |
#
# 参考: https://qiita.com/delphinus/items/cd221a450fd23506e81a

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''
hook_source = '''
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']


# Terraform
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf', 'terraform']
hook_source = '''
let g:terraform_fmt_on_save = 1
'''


# Typescript
[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_i = 1

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts', 'typescript']

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = ['ts', 'typescript']
hook_add = '''
  let g:nvim_typescript#default_mappings = 1
  let g:nvim_typescript#javascript_support = 1
'''
hook_post_update = '''
  let g:dein#plugin.build = './install.sh'
'''

# Ruby
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'takkii/Bignyanco'
