# hookの種類
#
# |   hookの名前   |            実行されるタイミング            |lazy OFF|lazy ON|
# |----------------|--------------------------------------------|--------|-------|
# |hook_add        |プラグインが dein.vim によって追加されたとき|OK      |OK     |
# |hook_source     |プラグインが読み込まれる直前                |NG      |OK     |
# |hook_post_source|プラグインが読み込まれた直後                |NG      |OK     |
# |hook_post_update|プラグインが更新された直後                  |OK      |OK     |
# |hook_done_update|プラグイン全ての更新が終わった直後          |OK      |OK     |
#
# 参考: https://qiita.com/delphinus/items/cd221a450fd23506e81a


# Dein
[[plugins]]
repo = 'Shougo/dein.vim'

# Denite
# 参考:
# https://zaief.jp/vim/denite/
# https://github.com/Shougo/denite.nvim/blob/master/doc/denite.txt
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
" Define mappings
nnoremap <silent> ,f :<C-u>Denite file/rec<CR>
nnoremap <silent> ,g :<C-u>Denite grep<CR>
nnoremap <silent> ,b :<C-u>Denite buffer<CR>
nnoremap <silent> ,l :<C-u>Denite line<CR>
'''
hook_source = '''
" Define denite key mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction

autocmd FileType define-fillter cll s:denite_filter_my_settings()
function! s:denite_filter_my_settings() abort
  imap <silent><buffer> <C-o> <Plug>(denite_filter_quit)
endfunction

" Change file/rec command.
call denite#custom#var('file/rec', 'command',
\ ['ag', '--hidden',  '--follow', '--nocolor', '--nogroup', '-g', ''])

" Ag command on grep source
call denite#custom#var('grep', {
  \ 'command': ['ag'],
  \ 'default_opts': ['-i', '--vimgrep', '--no-heading'],
  \ 'recursive_opts': [],
  \ 'pattern_opt': ['--regexp'],
  \ 'separator': ['--'],
  \ 'final_opts': []
  \ })

" Define aliases
call denite#custom#alias('source', 'file/rec/git', 'file/rec')
call denite#custom#var('file/rec/git', 'command',
  \ ['git', 'ls-files', '-co', '--exclude-standard'])

" Change default action. use split when opening file
call denite#custom#kind('file', 'default_action', 'split')
" Change default action. use floating
let s:denite_win_width_percent = 0.85
let s:denite_win_height_precent = 0.7
let s:denite_default_options = {
  \ 'split': 'floating',
  \ 'winwidth': float2nr(&columns * s:denite_win_width_percent),
  \ 'wincol': float2nr((&columns - (&columns * s:denite_win_width_percent)) / 2),
  \ 'winheight': float2nr(&lines * s:denite_win_height_precent),
  \ 'winrow': float2nr((&lines - (&lines * s:denite_win_height_precent)) / 2),
  \ 'highlight_filter_background': 'DeniteFilter',
  \ 'prompt': '$ ',
  \ 'start_filter': v:true,
  \ }
call denite#custom#option('default', s:denite_default_options)
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tomasr/molokai'
